#!/bin/bash
MAZAKODRON_DIR=~/git/mazakodron

mkdir output 2> /dev/null || rm output/*
for file in svg/*.svg
do
  name=${file##svg/}
  echo $name
  if [[ "x$1" != "x" ]]; then
    python $MAZAKODRON_DIR/przerabiator/mazakodron_przerabiator.py $file > .tmp.svg
  else
    cp $file .tmp.svg
  fi
  python $MAZAKODRON_DIR/punktowator/mazakodron_punktowator.py .tmp.svg > output/${name%.svg}.mzkdrn
  rm .tmp.svg
done
